# Generated by Django 4.0.5 on 2022-06-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.TextField(null=True)),
                ('wear', models.FloatField()),
                ('weather', models.FloatField()),
                ('vegetation', models.FloatField()),
                ('name', models.TextField()),
            ],
        ),
    ]
