# Generated by Django 4.0.5 on 2022-06-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_powerline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerline',
            name='geometry',
            field=models.JSONField(null=True),
        ),
    ]
